/*
  Name: QUEUESTUDENTS
  Copyright: 
  Author: S.HAREWOOD
  Date: 09/01/10 20:42
  Description: NOTE THAT IN THIS PROGRAM THE FILE ACTS AS THE QUEUE
*/
#include<stdio.h>
#include<errno.h>
#include<stdlib.h>
#include<stdbool.h>
#define string_length 30
#define LENGTH 100//NUMBER OF RECORDS IN THE FILE

  struct studentInfo{
    
         
	int studentAuto;//this is person's position in queue
    int id;// every record MUST have some varaible that uniquely identifies it.
           // The record are stored in the binary files based on this "primary key"
   
	char first_name[ string_length ];
	char last_name[ string_length ];
 
    char food [ string_length ];
    float price;
     };
//function genrerates and writes index to a file
int autocreateIndex(int autoGeneratedIndex)
{
  
    
    	FILE*fileIndex;
    	int index;
         if ((fileIndex = fopen("auto", "w"))==NULL)
        	{
        			printf("Cannot open file \n");
        			exit(1);
        	}
         else
         {   index=autoGeneratedIndex;
        
        	/*printing data tofile*/
          	 fprintf(fileIndex,"%d",index);//writes the generated index to the record.
             
        	 fclose(fileIndex);/*close file*/
        	 
          }
}//end function

//reads index from the file
int readAutoIndex()
{
   
    	FILE*readAutoIndex;
    	int autoIndex,ans;
    /* open file for reading */
       if ((readAutoIndex= fopen("auto", "r"))==NULL)
     	{
      		printf("Cannot open file \n");
      		exit(errno);
        }/*end if*/
 
     	else
        {
    
        	fscanf(readAutoIndex,"%d",&autoIndex);
            ans=autoIndex;
        		 
        	//read and display every line in the file
        	while(!feof(readAutoIndex))//while not the end of the file
        	{
                   fscanf(readAutoIndex,"%d",&autoIndex);
                   ans=autoIndex;
            }
         return ans;
         printf("ANS%d",ans);
         fclose(readAutoIndex);  /*close file*/

        }//end else
}//end function


 // checks if the queue is empty 
 bool isEmpty()
{
  		if(readAutoIndex()==-1)
   		  	return true;

  		else 

			return false;
}//  end isEmpty
	

//to determine the number of records in the fileS
int size()
{      int numRecords;
     
     
       numRecords=(readAutoIndex())+1;
     

        return (numRecords);

}//end size

//Function provides the user with a menu from which they can choose their options

int MenuChoice()
{
     int choice;//local variable which holds the option entered by the user
    
     printf("\n\n");
     printf("\n\n");
     printf("\n\n");
     
	
    
     printf("\n\n");
     printf("\n\n");
     printf("\n\n");

    printf("============================================================\n\n         ");
printf("OPTION              DESCRIPTION                   \n\n");
    printf("============================================================\n\n         ");
    
	printf("1               Create a new file\n\n");
	printf("         2               Add Student Information\n\n");
	
	printf("         3               Display student information \n\n");
 
 printf("        4               Delete a record\n\n ");
 printf("        5               Query number of records in the file\n \n");
   printf("        6               Check if file is empty\n \n");
	printf("         7               Exit program\n\n ");
   
	
	
     printf("============================================================\n\n         ");
	printf("=>=>=>=>=>=>=>ACADEMY OF MATH=>=>=>=>=>=>=>\n\n");
    printf("============================================================\n\n         ");


     printf("\n\n");
     printf("\n\n");
     printf("Task=====>");
    
    scanf("%d",&choice);
    
    return choice;// the option choice by the user is returned to main-the function that called it
}/*End Function*/



// "queues up"  records to file in the order entered
void enqueueStudentInfo(FILE*inDataFile1 , struct studentInfo student)
{

 
               if ((inDataFile1 = fopen("myfile5", "rb+"))==NULL)//open binary file for reading and writing
               {
                                printf("Cannot open file \n");
                                exit(1);
                }/*end if*/

              int Auto=readAutoIndex();  //get index from auto file
    
              if( Auto== (LENGTH-1))
                   printf("Queue full.");
              else
              {
                    
		        Auto= Auto+1;//determine position to write the entered record to in the file
		    
                       
                fseek(inDataFile1,( Auto)*sizeof(struct studentInfo),SEEK_SET);//find point in file to
                                                                                    //write the record
                fwrite(&student,sizeof(struct studentInfo),1,inDataFile1);//write the record
		       
                }//end else
                fclose(inDataFile1);//close the file   
                autocreateIndex(Auto);//write new value of index to the text file
  
}//end enqueueStudentInfo() 

              
//This function "dequeues" records from file
int dequeueStudentinfo(FILE*inDataFile1)
{              
                int g,val;
                FILE*inDataFile2;//another pointer to the file has been created
                struct studentInfo student={0,0,"","","",0.0}; 
                struct studentInfo blankStudent={0,0,"","","",0.0}; 
     
             //opening a pointer to the file         
            if ((inDataFile1 = fopen("myfile5", "rb+"))==NULL)
            {
                             printf("Cannot open file \n");
                             exit(1);
            }/*end if*/
         
          //opening another  pointer to the file  
            if ((inDataFile2 = fopen("myfile5", "rb+"))==NULL)
            {
                             printf("Cannot open file \n");
                             exit(1);
            }/*end if*/
             printf("============================================================\n\n         ");
printf("          \n\n\n\t\t\t DELETE RECORDS                 \n\n");
    printf("============================================================\n\n         "); 
         
             
            int deleteNum=readAutoIndex();//CALL TO FUNCTION WHICH RETURNS THE INDEX VALUE FROM THE AUTOFILE

	         
            if( deleteNum<0)/* Check for error situation*/
            {
                printf("FILE IS EMPTY. NO RECORDS PRESENT\n");
            }
        
        	else
            {
            		 
                fseek(inDataFile1,( 0)*sizeof(struct studentInfo),SEEK_SET);//SEEK RECORD TO DELETE,I.E THE FIRST RECORD 
                fread(&student,sizeof(struct studentInfo),1,inDataFile1);//READ RECORD TO DELETE
             /*Read Mode*/ 
                if(student.studentAuto==0)// IF THERE IS NO RECORD
                {
                        printf("============================================================\n\n         ");
                        printf("             !!!!!!RECORD DOES NOT EXIST!!!!!!                 \n\n");
                        printf("============================================================\n\n\n\n\n        ");
               
                }/*end if*/
              if(student.studentAuto!=0)//IF RECORD EXISTS
              {
                       fseek(inDataFile1,(1-1)*sizeof(struct studentInfo),SEEK_SET);
                       fwrite(&blankStudent,sizeof(struct studentInfo),1,inDataFile1);//OVERWRITE RECORD WITH A BLANK ONE
                       printf("============================================================\n\n         ");
                       printf("          \n\n\n\t\t\t DELETE COMPLETE                \n\n");
                       printf("============================================================\n\n         "); 
                       val=student.id;
          
                        
           
                       for(g=0;g<deleteNum;g++) //Moving up Records in file AFTER the delete
                       {
                                     fseek(inDataFile1,( g)*sizeof(struct studentInfo),SEEK_SET);//find   point  G in file 
                                     fseek(inDataFile2,( g+1)*sizeof(struct studentInfo),SEEK_SET);//find point (G+1) in file 
                                     fread(&student,sizeof(struct studentInfo),1,inDataFile2);    //READ  record IN SLOT (G+1) OF FILE 
                                     student.studentAuto=g+1;
                                     fwrite(&student,sizeof(struct studentInfo),1,inDataFile1);//write the record IN SLOT (G+1) OF FILE TO SLOT G                
                       }//end for
                       autocreateIndex(deleteNum-1);//index decremented by 1 after delete and its new value written to the file
            
             }  //end if          
             fclose(inDataFile1);//close pointer to the file
             fclose(inDataFile2);//close second pointer to the file
            
          
    } //end else       
   return val;        
} //end function 
       
 
 void view(FILE* inDataFile)//views the contents of the file
 {      
            struct studentInfo student={0,0,"","","",0.0};  

            int Auto=readAutoIndex ();//get index
            if ((inDataFile = fopen("myfile5", "rb+"))==NULL)
            {
                 printf("Cannot open file \n");
                 exit(1);
            }/*end if*/
	        printf("============================================================\n\n         ");
            printf("             \n\n\n\t\t\tVIEW RECORDS                 \n\n");
            printf("============================================================\n\n         ");
    
    

	/*read and display every line in the file*/
	
            while(!feof(inDataFile)&& student.studentAuto<=Auto)//WHILE THE END OF FILE HAS NOT BEEN REACHED
            {   
               fread(&student,sizeof(struct studentInfo),1,inDataFile);
               if(student.id!=0)
               {
                     printf("Position in file--->%d\n\tID---->%d\n\tNAME---->%s\t%s\n\Food Chosen----->%s\n\tPrice---->%3.2f",student.studentAuto,student.id,student.first_name,student.last_name,student.food,student.price);
               	     printf("\n\n\n");
              	     printf("\n\n");
                     printf("============================================================\n\n         ");
    
                }/*end if*/
    
           }/*end while*/
           fclose(inDataFile);//CLOSE FILE
  
}//end view Function   
  
int  main()
{   
	FILE*inDataFile1;
    int identification,result,f;
    float amount;
   
    	
   result=MenuChoice();/*call to function MenuChoice*/	
    
   while(result!=7){
   switch(result){	
   case 1:
   {//creates the binary file for writing
                      struct studentInfo student={0,0,"","","",0.0}; 

                      autocreateIndex(-1);//when file is FIRST created index is gigen a value of -1
  
                       /* open file for input */
                      if ((inDataFile1 = fopen("myfile5", "wb"))==NULL)
                      {
                                  printf("Cannot open file \n");
                                  exit(1);
                      }/*end if*/ 

                     else

                     {
                             
                              //creating 100 blank records
                              for (f=0;f<=100;f++)
                              {
                                     fwrite(&student,sizeof(struct studentInfo),1,inDataFile1);
                              } /*end for*/      
 
 
                              fclose(inDataFile1);//closes the file pointer
                     }/*end else*/
                       printf("============================================================\n\n         ");
                       printf("             FILE CREATED                 \n\n");
                       printf("============================================================\n\n         ");


                        result=MenuChoice();/*call to function MenuChoice*/
                        break;
}//end case 1 
 case 2://WRITING RECORDS
  {

               struct studentInfo student={0,0,"","","",0.0}; 
 
                if ((inDataFile1 = fopen("myfile5", "rb+"))==NULL)//open binary file for reading and writing
                {
                                printf("Cannot open file \n");
                                exit(1);
                }/*end if*/

                int passAuto=readAutoIndex();
         
                student.studentAuto=readAutoIndex()+2;
             
                printf("Enter student Id--->");
                scanf("%d",&student.id);
                
                printf("Enter first name--->");
                scanf("%s",&student.first_name);
    
                printf("Enter lastname---->");
                scanf("%s",&student.last_name);
    
                            
                printf("Enter name of food item---->");
                scanf("%s",&student.food);  
                
                printf("Enter price of item---->");
                scanf("%f",&student.price);  
    
                enqueueStudentInfo(inDataFile1 ,student);//call  to function which queues up the students in the file
             
                
    
    	         result=MenuChoice();/*call to function MenuChoice*/	 
                 break;	
}//END CASE 2		 
  

    
    
    case 3://READING RECORDS
    {	
                 view(inDataFile1);//call to function that displays the records
                 result=MenuChoice();/*call to function MenuChoice*/
                 break;
    }  //END  CASE 3



    case 4:
    {//DEQUEUING RECORDS
                 
                 int ids=dequeueStudentinfo(inDataFile1);  //CALL TO FUNCTION THAT REMOVES STUDENTS IN FILE.STUDENTS ARE REMOVED   
                                         //USING THE FIRST IN FIRST OUT PRINCIPLE(FIFO)
                                         
                 printf("\n\n");
                 printf("=======RECORD WITH ID \t%d HAS BEEN DELETED======\n\n",ids);
       
                 result=MenuChoice();/*call to function MenuChoice*/
                 break;
   }//end case 4


   case 5:
   {//Find number RECORDS
                 
        int numberRecords=size(); //CALL TO FUNCTION THAT RETURNS THE NUMBER OF RECORDS IN THE FILE   
        printf("============================================================\n\n         ");
	    printf("Number of records in the file---->%d\n\n",numberRecords);
        printf("============================================================\n\n         ");
   
    
        result=MenuChoice();/*call to function MenuChoice*/

        break;
  }//end case 5
  
  case 6:{//Determine if the file is empty
                 
      if (isEmpty()) //CALL TO FUNCTION THAT RETURNS THE NUMBER OF RECORDS IN THE FILE   
      {  printf("============================================================\n\n         ");
        	printf("===========================FILE IS EMPTY========================\n\n");
          printf("============================================================\n\n         ");
      }//end if 
   else
   {
            printf("============================================================\n\n         ");
        	printf("===========================FILE IS NOT EMPTY========================\n\n");
            printf("============================================================\n\n         ");
    }//end else             
     result=MenuChoice();/*call to function MenuChoice*/
     
    break;
} //end case 7             
 
case 8:
 
    {
       
       system("pause");
       return 0; 
      
      break;
    }//end case 8
      default: 
           printf("============================================================\n\n         ");
printf("             !!!!!!INVALID CHOICE!!!!!!                 \n");
    printf("============================================================\n\n\n\n\n        ");
        result=MenuChoice();/*call to function MenuChoice*/                                                          
 
  
break;                                                                             }
}
}//END PROGRAM

 
	
		  	 

         
         

